export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

  USER_INFO_FETCH: "USER_INFO_FETCH",
  USER_INFO_FETCH_SUCCESS: "USER_INFO_FETCH_SUCCESS",
  USER_INFO_FETCH_FAILAURE: "USER_INFO_FETCH_FAILAURE",
  USER_INFO_FETCH_UNAUTHORIZED: "USER_INFO_FETCH_UNAUTHORIZED",

  FETCH_CAMPAGIN_LIST: "FETCH_CAMPAGIN_LIST",
  FETCH_CAMPAGIN_LIST_SUCCESS: "FETCH_CAMPAGIN_LIST_SUCCESS",
  FETCH_CAMPAGIN_LIST_FAILAURE: "FETCH_CAMPAGIN_LIST_FAILAURE",

  SET_CAMPAGIN_LIST_PAGINATION_VALUE_SUCCESS:
    "SET_CAMPAGIN_LIST_PAGINATION_VALUE_SUCCESS",
  SET_CAMPAGIN_LIST_PAGINATION_VALUE_FAILURE:
    "SET_CAMPAGIN_LIST_PAGINATION_VALUE_FAILURE",

  SET_CAMPAGIN_LIST_SEARCH_TERM_SUCCESS:
    "SET_CAMPAGIN_LIST_SEARCH_TERM_SUCCESS",
  SET_CAMPAGIN_LIST_SEARCH_TERM_FAILURE:
    "SET_CAMPAGIN_LIST_SEARCH_TERM_FAILURE",

  FETCH_CONSENT: "FETCH_CONSENT",
  FETCH_CONSENT_LIST_SUCCESS: "FETCH_CONSENT_LIST_SUCCESS",
  FETCH_CONSENT_LIST_FAILED: "FETCH_CONSENT_LIST_FAILED",
  FETCH_CONSENT_LIST_DELETE: "FETCH_CONSENT_LIST_DELETE",
  ADD_TO_CONSENT_LIST: "ADD_TO_CONSENT_LIST",
  SET_CONSENT_LIST_EDIT: "SET_CONSENT_LIST_EDIT",
  SET_CONSENT_LIST_VIEW: "SET_CONSENT_LIST_VIEW",
  SET_CONSENT: "SET_CONSENT",
};
